### ISSUE TITLE
The "Microsoft.Build.Tasks.Git.LocateRepository" task failed unexpectedly. System.InvalidCastException

### ISSUE THREAD

**Issue by maraf** [dotnet/sourcelink#1007]
Hitting this error in SDK build [247607](https://dev.azure.com/dnceng-public/public/_build/results?buildId=247607&view=results)

```
.dotnet/sdk/8.0.100-preview.4.23220.14/Sdks/Microsoft.Build.Tasks.Git/build/Microsoft.Build.Tasks.Git.targets(26,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Build) The "Microsoft.Build.Tasks.Git.LocateRepository" task failed unexpectedly.
System.InvalidCastException: [A]System.Runtime.CompilerServices.StrongBox`1[Microsoft.Build.Tasks.Git.GitRepository] cannot be cast to [B]System.Runtime.CompilerServices.StrongBox`1[Microsoft.Build.Tasks.Git.GitRepository]. Type A originates from 'System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' in the context 'Default' at location '/mnt/vss/_work/1/s/.dotnet/shared/Microsoft.NETCore.App/8.0.0-preview.4.23220.4/System.Private.CoreLib.dll'. Type B originates from 'System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' in the context 'Default' at location '/mnt/vss/_work/1/s/.dotnet/shared/Microsoft.NETCore.App/8.0.0-preview.4.23220.4/System.Private.CoreLib.dll'.
   at Microsoft.Build.Tasks.Git.RepositoryTask.TryGetCachedRepositoryInstance(String cacheKey, Boolean requireCached, GitRepository& repository)
   at Microsoft.Build.Tasks.Git.RepositoryTask.GetOrCreateRepositoryInstance()
   at Microsoft.Build.Tasks.Git.RepositoryTask.ExecuteImpl()
   at Microsoft.Build.Tasks.Git.RepositoryTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

**Comment by tmat** [comment]
@rainersigwald

**Comment by tmat** [comment]
Seems like the same as https://github.com/dotnet/msbuild/issues/8478
