### ISSUE TITLE
Support for TFVC

### ISSUE THREAD

**Issue by ipjohnson** [dotnet/sourcelink#122]
Currently we use TFVC on premise for our source control. We also package our shared code into nuget packages to share between projects. Currently it's impossible to debug as we don't want to run our own symbol server. 

Adding support for TVFC to Source Link would solve a major problem for us as well as make TFVC supported on the same level as git.

**Comment by BennyBread** [comment]
Hi, we'd also really appreciate this feature.
I just want to mention that I testet a hours ago the SourceLink.Vsts.Tfvc preview plugin but got build errors:

The version 1.0.0-beta2-18623-01 has a reference to Microsot.Build.Task.Tfvc 10.00-beta2-18623-01

The first problem is the Microsoft.Build.Tasks.Tfvc.dll is not found because it is looking for a version in the directory "net461" which does not exist. 
-> I copied the directory "net46" to net461.  => Now it goes a little deeper down the rabbit hole:

These errors happen during build inside VS2017 15.9.6:

```
1>C:\Users\meiner\.nuget\packages\microsoft.build.tasks.tfvc\1.0.0-beta2-18623-01\build\Microsoft.Build.Tasks.Tfvc.targets(28,5): error MSB4018: The "Microsoft.Build.Tasks.Tfvc.GetRepositoryUrl" task failed unexpectedly.
1>C:\Users\meiner\.nuget\packages\microsoft.build.tasks.tfvc\1.0.0-beta2-18623-01\build\Microsoft.Build.Tasks.Tfvc.targets(28,5): error MSB4018: System.ArgumentException: The string must have at least one character.
1>C:\Users\meiner\.nuget\packages\microsoft.build.tasks.tfvc\1.0.0-beta2-18623-01\build\Microsoft.Build.Tasks.Tfvc.targets(28,5): error MSB4018: Parameter name: name
1>C:\Users\meiner\.nuget\packages\microsoft.build.tasks.tfvc\1.0.0-beta2-18623-01\build\Microsoft.Build.Tasks.Tfvc.targets(28,5): error MSB4018:    at Microsoft.VisualStudio.Services.Common.ArgumentUtility.CheckStringForNullOrEmpty(String stringVar, String stringVarName, Boolean trim, String expectedServiceArea)
1>C:\Users\meiner\.nuget\packages\microsoft.build.tasks.tfvc\1.0.0-beta2-18623-01\build\Microsoft.Build.Tasks.Tfvc.targets(28,5): error MSB4018:    at Microsoft.TeamFoundation.VersionControl.Client.VersionControlServer.TryGetTeamProject(String name)
1>C:\Users\meiner\.nuget\packages\microsoft.build.tasks.tfvc\1.0.0-beta2-18623-01\build\Microsoft.Build.Tasks.Tfvc.targets(28,5): error MSB4018:    at Microsoft.TeamFoundation.VersionControl.Client.VersionControlServer.TryGetTeamProjectForServerPath(String serverPath)
1>C:\Users\meiner\.nuget\packages\microsoft.build.tasks.tfvc\1.0.0-beta2-18623-01\build\Microsoft.Build.Tasks.Tfvc.targets(28,5): error MSB4018:    at Microsoft.TeamFoundation.VersionControl.Client.VersionControlServer.GetTeamProjectForServerPath(String serverPath)
1>C:\Users\meiner\.nuget\packages\microsoft.build.tasks.tfvc\1.0.0-beta2-18623-01\build\Microsoft.Build.Tasks.Tfvc.targets(28,5): error MSB4018:    at Microsoft.TeamFoundation.VersionControl.Client.Workspace.GetTeamProjectForLocalPath(String localPath)
1>C:\Users\meiner\.nuget\packages\microsoft.build.tasks.tfvc\1.0.0-beta2-18623-01\build\Microsoft.Build.Tasks.Tfvc.targets(28,5): error MSB4018:    at Microsoft.Build.Tasks.Tfvc.GetRepositoryUrl.Execute(WorkspaceInfo workspaceInfo)
1>C:\Users\meiner\.nuget\packages\microsoft.build.tasks.tfvc\1.0.0-beta2-18623-01\build\Microsoft.Build.Tasks.Tfvc.targets(28,5): error MSB4018:    at Microsoft.Build.Tasks.Tfvc.RepositoryTask.Execute()
1>C:\Users\meiner\.nuget\packages\microsoft.build.tasks.tfvc\1.0.0-beta2-18623-01\build\Microsoft.Build.Tasks.Tfvc.targets(28,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Users\meiner\.nuget\packages\microsoft.build.tasks.tfvc\1.0.0-beta2-18623-01\build\Microsoft.Build.Tasks.Tfvc.targets(28,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

```

Is there a time plan for the milestone 1.0.0 ?

**Comment by tmat** [comment]
The current implementation of TFVC Source Link package is not functional. 

> Is there a time plan for the milestone 1.0.0 ?

No time plan. Whenever we think it's stable enough. We are still looking into xplat issues and I'd also like to finish TFVC implementation before we declare 1.0.0.

**Comment by ipjohnson** [comment]
Not gonna lie exceptionally disappointing that you aren’t treating TFVC as a first class solution.

I opened this 7 months ago and haven’t seen any movement at all.

**Comment by JamesMiera** [comment]
We could also very much use this.

**Comment by dsoltesz** [comment]
We need this as well...any work being done on this issue?

**Comment by jeremymwilton** [comment]
Any update on this issue or are there workarounds?

**Comment by tmat** [comment]
No update yet. It's definitely on our backlog.

**Comment by ipjohnson** [comment]
@tmat this was logged 18 months ago. Is there any news/progress?

**Comment by tmat** [comment]
@ipjohnson Unfortunately not. TFVC support is currently not high enough in our prioritized list and it won't make it for 1.0.0.

**Comment by TheXenocide** [comment]
This would also help us

**Comment by ipjohnson** [comment]
This issue was opened nearly two years ago. What’s it say about the future of TFVC if they aren’t willing to support it in their own products?

**Comment by TheXenocide** [comment]
I mean I'm already an advocate for moving our code to git, but it's a very large multi-project codebase with scripts that understand the branching structure and everything so it would be a rather costly transition for us at the moment. That said, I don't really have an interest in the future of TFVC (just one more point in favor of my argument to migrate away from it). For us this would just be nice to be able to use in the meantime; today I wouldn't use TFVC if it weren't forced on me, and I don't think the general guidance is to use it on new projects anyway so what you're implying here isn't really a new concern. 

Legacy compatibility is one thing, but new feature development is another. I'm not sure I would say our company's unwillingness to migrate to more current technologies is necessarily a sufficient reason for Microsoft to continue to bear the burden of focusing their priorities on supporting new features for us just because we won't do it ourselves. It would be nice to have. That's my only reason for being here. I'm sure if it was important enough for you then over the course of two years you could have found the time to submit a pull request or, given two years time, if it's important enough to us we could probably get migrated over to git. I'm not trying to be rude, but your presumably rhetorical question comes off as a bit entitled to me so I thought I'd make it clear what *my* interest is in commenting on the ticket. We have to remember that there are a *lot* of priorities to juggle out there; we feel it where I work, I'm guessing you feel it where you work. It can be frustrating to not be the most important customer on the block, but I don't think treating them like they owe us something that didn't exist when we made our technical decisions is really a helpful way to approach the conversation.

Is there somebody who could let us know what kind of work would be involved in getting this working? Are there any prototypes or in-progress elements to look at? Were there unsolved challenges in previous efforts to look at this? What would someone considering contributing a pull request want to reference to get started? I believe I remember seeing a beta package or something while I was initially looking for this; maybe we can help pull it across the line?

**Comment by tmat** [comment]
@TheXenocide Thanks for the comment. The prototype of the package is still in this repo, under https://github.com/dotnet/sourcelink/tree/master/src/SourceLink.AzureRepos.Tfvc. We would absolutely accept a PR. The one thing that needs to be done carefully is caching the source control information retrieved from the server during the build. It would be very inefficient to query the server for every project. Instead, the task should use an msbuild cache that allows to share info across the entire build.

Another thing that has been a problem for us is testing. Unlike git testing TFVC to be installed to our CI servers. I don't think it's possible to install it in a container, unfortunately. So we would likely need to maintain a TFVC instance in our Azure DevOps.

I'd accept the PR if it did some reasonable mocking of the TFVC APIs and had no end-to-end test, as long as the author manually tests the implementation.

**Comment by TheXenocide** [comment]
Ah, is there a mechanism you're aware of for that form of caching? We've actually had exactly that concern in other build scripts and didn't find a solution back when we had the issue. Apparently, once upon a time you could use AppDomain.Current.SetData because they were all run in the same process and AppDomain, but now each project build appears to be isolated.

**Comment by tmat** [comment]
There are two approaches I know of. One is to use MSBuild task on a project like so:

https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/RepositoryInfo.targets#L112-L118

Whenever msbuild executes a project build it adds the result in the cache keyed by the project path and a set of global properties. In the above example you can see the target changing the list of properties in order to get the desired caching key. Although the target `_RepositoryValidation` is invoked for every project in the solution being built, it only executes ones for each distinct set of values of the global properties.

The other approach is to use GetRegisteredTaskObject method like so: https://github.com/dotnet/sourcelink/blob/master/src/Microsoft.Build.Tasks.Git/RepositoryTask.cs#L135. This is an API available to a task implementation.

**Comment by TheXenocide** [comment]
I don't have a ton of spare time, but I have at least started dabbling with the MSBuild techniques you've mentioned to get a better handle on how they work.

**Comment by adamralph** [comment]
> There are two approaches I know of. One is to use MSBuild task on a project like so:
> 
> https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/RepositoryInfo.targets#L112-L118

@tmat the file has moved on since then. This is why it's good to use absolute links. The version you are referring to is:

https://github.com/dotnet/arcade/blob/b1bb51dfdb444a0ae7053cb93a2b83549c15170f/src/Microsoft.DotNet.Arcade.Sdk/tools/RepositoryInfo.targets#L112-L118

**Comment by StevenBonePgh** [comment]
@prnadago On April 20, 2021 you said "[We’re still committed to support TFVC in Visual Studio.](https://devblogs.microsoft.com/visualstudio/visual-studio-2022/#comment-24682)" 

According to @tmat above, it sounds like what needs done is well understood.  Can you please put some resources on this? I'd really like to see you put some into action your statement referenced above.

**Comment by mAcf00bar** [comment]
So, again more than a year and still an open issue ;-(
I'd love to migrate to git but at my new shop, it doesn't look like its going to happen soon.
