### ISSUE TITLE
Update-Package -reinstall or Uninstall-Package won't work for .NET Framework projects

### ISSUE THREAD

**Issue by xied75** [dotnet/sourcelink#141]
To repo:
Visual Studio 2017, start a new .NET Framework Library project targeting .NET 4.5 or 4.0.
Install Microsoft.SourceLink.Github from Package Manager Console.
Build, get error
```
error : Unable to locate repository containing directory 'c:\scratch\ClassLibrary4\ClassLibrary4
```
which is fine, we don't have github set up for this project yet.

But then if you call __Update-Package -reinstall__ or __Uninstall-Package__, it would give errors like this:

```
PM> update-package -reinstall


Attempting to gather dependency information for multiple packages with respect to project 'ClassLibrary4', targeting '.NETFramework,Version=v4.5'
Gathering dependency information took 1.07 sec
Attempting to resolve dependencies for multiple packages.
Resolving dependency information took 0 ms
Resolving actions install multiple packages
Retrieving package 'Microsoft.Build.Tasks.Git 1.0.0-beta-62925-02' from 'nuget.org'.
Retrieving package 'Microsoft.SourceLink.Common 1.0.0-beta-62925-02' from 'nuget.org'.
Retrieving package 'Microsoft.SourceLink.GitHub 1.0.0-beta-62925-02' from 'nuget.org'.
Removed package 'Microsoft.SourceLink.GitHub 1.0.0-beta-62925-02' from 'packages.config'
Successfully uninstalled 'Microsoft.SourceLink.GitHub 1.0.0-beta-62925-02' from ClassLibrary4
Removed package 'Microsoft.SourceLink.Common 1.0.0-beta-62925-02' from 'packages.config'
Successfully uninstalled 'Microsoft.SourceLink.Common 1.0.0-beta-62925-02' from ClassLibrary4
Removed package 'Microsoft.Build.Tasks.Git 1.0.0-beta-62925-02' from 'packages.config'
Install failed. Rolling back...
Package 'Microsoft.Build.Tasks.Git 1.0.0-beta-62925-02' already exists in folder 'c:\scratch\ClassLibrary4\packages'
Added package 'Microsoft.Build.Tasks.Git 1.0.0-beta-62925-02' to 'packages.config'
Package 'Microsoft.SourceLink.Common 1.0.0-beta-62925-02' already exists in folder 'c:\scratch\ClassLibrary4\packages'
Added package 'Microsoft.SourceLink.Common 1.0.0-beta-62925-02' to 'packages.config'
Package 'Microsoft.SourceLink.GitHub 1.0.0-beta-62925-02' already exists in folder 'c:\scratch\ClassLibrary4\packages'
Added package 'Microsoft.SourceLink.GitHub 1.0.0-beta-62925-02' to 'packages.config'
Executing nuget actions took 883.56 ms
update-package : The result "" of evaluating the value "$(MicrosoftBuildTasksGitAssemblyFile)" of the "AssemblyFile" attribute in element <UsingTask> is not valid.  
c:\scratch\ClassLibrary4\packages\Microsoft.Build.Tasks.Git.1.0.0-beta-62925-02\build\Microsoft.Build.Tasks.Git.targets
At line:1 char:1
+ update-package -reinstall
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
 
Time Elapsed: 00:00:02.2867668
```

Manually removing packages from NuGet Package Manager UI, could remove the other two but __Microsoft.Build.Tasks.Git__ refuses to go.

**Comment by edmistone** [comment]
The only way I was able to get rid of it was by manually deleting the files. I also had to go into the .csproj file for my project and delete any references to it. I then reinstalled it from the NuGet Package Manager UI, and it seems to be working now.

**Comment by tmat** [comment]
NuGet Package Manager reports the following error when uninstalling the package via VS UI:

```
Microsoft.Build.Exceptions.InvalidProjectFileException: The result "" of evaluating the value "$(_MicrosoftSourceLinkCommonAssemblyFile)" of the "AssemblyFile" attribute in element <UsingTask> is not valid.  C:\Temp\Cpp2\ConsoleApplication1\packages\Microsoft.SourceLink.Common.1.0.0-ci\build\InitializeSourceControlInformation.targets
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.VerifyThrowInvalidProject[T1,T2,T3,T4](Boolean condition, String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1, T3 arg2, T4 arg3)
   at Microsoft.Build.Execution.TaskRegistry.RegisterTasksFromUsingTaskElement[P,I](ILoggingService loggingService, BuildEventContext buildEventContext, String directoryOfImportingFile, ProjectUsingTaskElement projectUsingTaskXml, TaskRegistry taskRegistry, Expander`2 expander, ExpanderOptions expanderOptions, IFileSystem fileSystem)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateUsingTaskElement(String directoryOfImportingFile, ProjectUsingTaskElement projectUsingTaskElement)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at NuGet.PackageManagement.VisualStudio.MicrosoftBuildEvaluationProjectUtility.RemoveImportStatement(Project msBuildProject, String targetsPath)
   at NuGet.PackageManagement.VisualStudio.CpsProjectSystem.<>c__DisplayClass5_0.<RemoveImportStatementAsync>b__0(Project buildProject)
   at NuGet.VisualStudio.ProjectHelper.<DoWorkInWriterLockAsync>d__0.MoveNext()
```

**Comment by tmat** [comment]
Filed https://github.com/NuGet/Home/issues/7347.
