### ISSUE TITLE
Sourcelink failing on RHEL 6 and Ubuntu 18

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sourcelink#204]
We are getting errors like the following when trying to build our repos using sourcelink on RHEL 6 and Ubuntu 18:

> /opt/code/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta-63401-01/build/Microsoft.Build.Tasks.Git.targets(20,5): The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
   at LibGit2Sharp.Core.NativeMethods.git_buf_free(GitBuf buf)
   at LibGit2Sharp.Core.Proxy.git_buf_free(GitBuf buf)
   at LibGit2Sharp.Core.Handles.GitBuf.Dispose()
   at LibGit2Sharp.Core.Proxy.ConvertPath(Func`2 pathRetriever)
   at LibGit2Sharp.Core.Proxy.git_repository_discover(FilePath start_path)
   at LibGit2Sharp.Repository.Discover(String startingPath)
   at Microsoft.Build.Tasks.Git.GitOperations.LocateRepository(String directory) in /_/src/Microsoft.Build.Tasks.Git.Operations/GitOperations.cs:line 26
   at Microsoft.Build.Tasks.Git.RepositoryTasks.LocateRepository(LocateRepository task) in /_/src/Microsoft.Build.Tasks.Git.Operations/RepositoryTasks.cs:line 58 [/opt/code/test/Microsoft.DotNet.Tools.Tests.Utilities/Microsoft.DotNet.Tools.Tests.Utilities.csproj]

**Comment by bording** [comment]
See #197

**Comment by tmat** [comment]
Should be fixed in version 1.0.0-beta2-18618-05
