### ISSUE TITLE
NullReferenceException in Microsoft.Build.Tasks.Git.GetSourceRoots

### ISSUE THREAD

**Issue by xoofx** [dotnet/sourcelink#285]
Hey,

On my repository [CppAst](https://github.com/xoofx/CppAst) I'm getting the following error when trying to use sourcelink:

```
1>C:\Users\alexa\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta2-19270-01\build\Microsoft.Build.Tasks.Git.targets(32,5): error MSB4018: The "Microsoft.Build.Tasks.Git.GetSourceRoots" task failed unexpectedly.
1>C:\Users\alexa\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta2-19270-01\build\Microsoft.Build.Tasks.Git.targets(32,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object.
1>C:\Users\alexa\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta2-19270-01\build\Microsoft.Build.Tasks.Git.targets(32,5): error MSB4018:    at Microsoft.Build.Tasks.Git.GitOperations.NormalizeUrl(String url, String root)
1>C:\Users\alexa\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta2-19270-01\build\Microsoft.Build.Tasks.Git.targets(32,5): error MSB4018:    at Microsoft.Build.Tasks.Git.GitOperations.GetSourceRoots(IRepository repository, Action`2 logWarning, Func`2 fileExists)
1>C:\Users\alexa\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta2-19270-01\build\Microsoft.Build.Tasks.Git.targets(32,5): error MSB4018:    at Microsoft.Build.Tasks.Git.RepositoryTasks.<>c.<GetSourceRoots>b__4_0(Repository repo, GetSourceRoots t)
1>C:\Users\alexa\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta2-19270-01\build\Microsoft.Build.Tasks.Git.targets(32,5): error MSB4018:    at Microsoft.Build.Tasks.Git.RepositoryTasks.Execute[T](T task, Action`2 action)
1>C:\Users\alexa\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta2-19270-01\build\Microsoft.Build.Tasks.Git.targets(32,5): error MSB4018:    at Microsoft.Build.Tasks.Git.RepositoryTasks.GetSourceRoots(GetSourceRoots task)
1>C:\Users\alexa\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta2-19270-01\build\Microsoft.Build.Tasks.Git.targets(32,5): error MSB4018:    at Microsoft.Build.Tasks.Git.GetSourceRoots.Execute()
1>C:\Users\alexa\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta2-19270-01\build\Microsoft.Build.Tasks.Git.targets(32,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Users\alexa\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta2-19270-01\build\Microsoft.Build.Tasks.Git.targets(32,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
``` 

I have the following SDKs installed:

```
$ dotnet --list-sdks
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.300 [C:\Program Files\dotnet\sdk]
2.1.400 [C:\Program Files\dotnet\sdk]
2.1.402 [C:\Program Files\dotnet\sdk]
2.1.502 [C:\Program Files\dotnet\sdk]
2.1.503 [C:\Program Files\dotnet\sdk]
2.1.600-preview-009497 [C:\Program Files\dotnet\sdk]
2.1.700-preview-009597 [C:\Program Files\dotnet\sdk]
2.1.700-preview-009601 [C:\Program Files\dotnet\sdk]
2.2.100 [C:\Program Files\dotnet\sdk]
3.0.100-preview-009812 [C:\Program Files\dotnet\sdk]
3.0.100-preview-010184 [C:\Program Files\dotnet\sdk]
```

**Comment by xoofx** [comment]
Incidentally, after removing a second `<PackageId ...>`  which was conditional in the file, sourcelink seems to be working now...

**Comment by tmat** [comment]
@xoofx Odd. Can you reproduce with the latest Source Link version? 1.0.0-beta2-19324-01

**Comment by xoofx** [comment]
Closing as it was fixed by removing the conditional, haven't had the time to check further
