### ISSUE TITLE
1.0.0-beta2-19351-01 and Microsoft.Build.Tasks.Git.LocateRepository task failed unexpectedly

### ISSUE THREAD

**Issue by wjvii** [dotnet/sourcelink#337]
Had a project using version 1.0.0-beta-63127-02 and updated to 1.0.0-beta2-19351-01 and started experiencing this error. I have tried this on three different project types, .NET Standard and .NET Framework and it occurs on both. I also tried a .NET Standard with targetframeowrk set to net472 and same issue. These were all brand new projects in the same git repo.

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "Microsoft.Build.Tasks.Git.LocateRepository" task failed unexpectedly.
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.Build.Tasks.Git.GitEnvironment.FindSystemDirectory() in /_/src/Microsoft.Build.Tasks.Git/GitDataReader/GitEnvironment.cs:line 88
   at Microsoft.Build.Tasks.Git.GitEnvironment.CreateFromProcessEnvironment() in /_/src/Microsoft.Build.Tasks.Git/GitDataReader/GitEnvironment.cs:line 79
   at Microsoft.Build.Tasks.Git.GitEnvironment.Create(String configurationScope) in /_/src/Microsoft.Build.Tasks.Git/GitDataReader/GitEnvironment.cs:line 64
   at Microsoft.Build.Tasks.Git.RepositoryTask.GetOrCreateRepositoryInstance() in /_/src/Microsoft.Build.Tasks.Git/RepositoryTask.cs:line 112
   at Microsoft.Build.Tasks.Git.RepositoryTask.ExecuteImpl() in /_/src/Microsoft.Build.Tasks.Git/RepositoryTask.cs:line 65
   at Microsoft.Build.Tasks.Git.RepositoryTask.Execute() in /_/src/Microsoft.Build.Tasks.Git/RepositoryTask.cs:line 43
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	NuGetStandardTest	C:\Users\wjvii\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta2-19351-01\build\Microsoft.Build.Tasks.Git.targets	24

**Comment by jcouv** [comment]
I'm getting this as well: https://github.com/dotnet/roslyn/issues/28916

**Comment by tmat** [comment]
@jcouv Git installation shouldn't be necessary. This is a bug.

**Comment by CreateAndInject** [comment]
I reproduce this bug also, I clone a repository and can't build since this issue.
