### ISSUE TITLE
Throw better error when git.exe cannot be found

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/sourcelink#350]
Currently, this unhelpful error message is thrown from here:

https://github.com/dotnet/sourcelink/blob/master/src/Microsoft.Build.Tasks.Git/GitDataReader/GitEnvironment.cs#L125

```
Error	MSB4018	The "Microsoft.Build.Tasks.Git.LocateRepository" task failed unexpectedly.
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.Build.Tasks.Git.GitEnvironment.FindSystemDirectory() in /_/src/Microsoft.Build.Tasks.Git/GitDataReader/GitEnvironment.cs:line 88
   at Microsoft.Build.Tasks.Git.GitEnvironment.CreateFromProcessEnvironment() in /_/src/Microsoft.Build.Tasks.Git/GitDataReader/GitEnvironment.cs:line 79
   at Microsoft.Build.Tasks.Git.GitEnvironment.Create(String configurationScope) in /_/src/Microsoft.Build.Tasks.Git/GitDataReader/GitEnvironment.cs:line 64
   at Microsoft.Build.Tasks.Git.RepositoryTask.GetOrCreateRepositoryInstance() in /_/src/Microsoft.Build.Tasks.Git/RepositoryTask.cs:line 112
   at Microsoft.Build.Tasks.Git.RepositoryTask.ExecuteImpl() in /_/src/Microsoft.Build.Tasks.Git/RepositoryTask.cs:line 65
   at Microsoft.Build.Tasks.Git.RepositoryTask.Execute() in /_/src/Microsoft.Build.Tasks.Git/RepositoryTask.cs:line 43
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	EFCore.Analyzers	C:\Users\Erik\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta2-19351-01\build\Microsoft.Build.Tasks.Git.targets	24	


```

Related issue: https://github.com/aspnet/EntityFrameworkCore/issues/16656

**Comment by tmat** [comment]
Dup of https://github.com/dotnet/sourcelink/issues/337.

**Comment by ErikEJ** [comment]
Sorry, but I cannot see an improved error message in the fix !?

**Comment by ErikEJ** [comment]
Ah, got is not required at all!!
